version: '3.1'

services:
  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - nodeapi
    container_name: devops-nginx
    hostname: reverseproxy
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    restart: on-failure
    ports:
      # Host:Client
      - 3000:3000 
  
  nodeapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - redis
    container_name: devops-nodeapi
    hostname: nodeapi
    environment:
      #Postgresql db
      - DB_HOST=postgres  
      - DB_PORT=5432     
      - DB_USER=theejkb
      - DB_PASSWORD=azertyuiop
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - ./node_modules
    restart: on-failure
  postgres:
    image: postgres:alpine
    container_name: devops-postgres
    environment:
      POSTGRES_USER: theejkb
      POSTGRES_PASSWORD: azertyuiop
      PGDATA: /data/postgres
    restart: on-failure
    volumes:
      - ./postgres-persistant-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine3.11
    container_name: devops-redis
    restart: on-failure
    hostname: redis-host